### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PNPyrenees** [plantnet/malpolon#64]
Dear,

I am trying to play with Malpolon without great experience in CNN.

My objective is to generate a distribution model for one species and compare the result with other SDM engine. 
I have 42 environmental variable (without sentinel data)

For the configuration, I was inspired by this example (https://github.com/plantnet/malpolon/tree/main/examples/custom_train/sentinel-2a-rgbnir_bioclim) and I custom the configuration file like this :

```
hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

run:
  predict: false
  #checkpoint_path: 'outputs/and.cyl/train_binary/last.ckpt'
  checkpoint_path: null

data:
  num_classes: &num_classes 5
  train_batch_size: 2
  inference_batch_size: 2
  num_workers: 8
  dataset_kwargs:
    - callable: "RasterBioclim"
      kwargs:
        root: "dataset/env_data/"
        labels_name: "../20240212-Extraction_GN-and.cyl-subset.csv"
        query_units: "pixel"
        query_crs: 4326
        patch_size: 128
        filename_regex: '(?P<band>bio_[\d])_crop_sample'  # single quotes are mandatory
        bands: ["bio_1", "bio_2", "bio_3", "bio_4", "bio_5", "bio_6", "bio_7", "bio_8", "bio_9", "bio_10", "bio_11", "bio_12", "bio_13", "bio_14", "bio_15", "bio_16", "bio_17", "bio_18", "bio_19", "bio_20", "bio_21", "bio_22", "bio_23", "bio_24", "bio_25", "bio_26", "bio_27", "bio_28", "bio_29", "bio_30", "bio_31", "bio_32", "bio_33", "bio_34", "bio_35", "bio_36", "bio_37", "bio_38", "bio_39", "bio_40", "bio_41", "bio_42"]
        obs_data_columns: {'x': 'longitude',
                           'y': 'latitude',
                           'index': 'index',
                           'species_id': 'species_id',
                           'split': 'subset'}
    #- callable: "PatchesDataset"
    #  kwargs:
    #    occurrences: "dataset/20240212-Extraction_GN-and.cyl-subset.csv"
    #    providers:
    #      - callable: "JpegPatchProvider"
    #        kwargs:
    #          root_path: "dataset/satellite_patches/"
    #          dataset_stats: 'jpeg_patches_sample_stats.csv'
    #          id_getitem: "surveyId"
    #          size: 128
    #          select: ['red', 'green', 'blue', 'nir']
    #    item_columns: ['longitude', 'latitude', 'surveyId']

task:
  task: "classification_binary" # ['classification_binary', 'classification_multiclass', 'classification_multilabel']

trainer:
  #accelerator: "gpu"
  accelerator: "cpu"
  devices: 'auto'
  max_epochs: 5
  # val_check_interval: 2
  check_val_every_n_epoch: 1
  log_every_n_steps: 10

model:
  provider_name: "timm" # choose from ["timm", "torchvision"]
  model_name: "resnet18"
  model_kwargs:
    pretrained: true # Deprecated in torchvision since 0.13 (replaced by "weights") but used by timm
    num_classes:
    in_chans:
    output_stride:
    global_pool:
  modifiers:
    change_first_convolutional_layer:
      num_input_channels: 42 # nombre de couche de donnnées d'environnement
    change_last_layer:
      num_outputs: *num_classes

optimizer:
  lr: 1e-2
  weight_decay: 0
  momentum: 0.9
  nesterov: true
  metrics:
    # binary_accuracy:
    #   # callable: 'Fmetrics.accuracy'
    #   kwargs: {}
    # multiclass_accuracy:
    #   # callable: 'Fmetrics.classification.multiclass_accuracy'
    #   kwargs:
    #     num_classes: *num_classes
    multilabel_accuracy:
      # callable: 'Fmetrics.classification.multilabel_accuracy'
      kwargs:
        num_labels: *num_classes
```

I didn't change the python script (https://github.com/plantnet/malpolon/blob/main/examples/custom_train/sentinel-2a-rgbnir_bioclim/cnn_on_rgbnir_concat.py) except changing the name of the file to "cnn_on_varenv.py"
When i try to run the python script, i have error returned 

```
Matplotlib created a temporary cache directory at /tmp/matplotlib-5e8sftwq because the default path (/home/geonatureadmin/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/lightning_fabric/loggers/csv_logs.py:268: Experiment logs directory /home/geonatureadmin/malpolon/outputs/cnn_on_varenv/2024-09-13_15-32-49/ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
[2024-09-13 15:32:49,616][timm.models._builder][INFO] - Loading pretrained weights from Hugging Face hub (timm/resnet18.a1_in1k)
[2024-09-13 15:32:49,785][timm.models._hub][INFO] - [timm/resnet18.a1_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/geonatureadmin/malpolon/outputs/cnn_on_varenv/2024-09-13_15-32-49 exists and is not empty.

  | Name  | Type              | Params | Mode 
----------------------------------------------------
0 | model | ResNet            | 11.2 M | train
1 | loss  | BCEWithLogitsLoss | 0      | train
----------------------------------------------------
11.2 M    Trainable params
0         Non-trainable params
11.2 M    Total params
44.779    Total estimated model params size (MB)
95        Modules in train mode
0         Modules in eval mode
Sanity Checking DataLoader 0:   0%|                                                                                                                                 | 0/2 [00:00<?, ?it/s]Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/geonatureadmin/malpolon/cnn_on_varenv.py", line 91, in main
    trainer.fit(classif_system, datamodule=datamodule, ckpt_path=classif_system.checkpoint_path)
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self._run_sanity_check()
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1052, in _run_sanity_check
    val_loop.run()
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 178, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 319, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 411, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/malpolon/models/standard_prediction_systems.py", line 169, in validation_step
    return self._step("val", batch, batch_idx)
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/malpolon/models/standard_prediction_systems.py", line 149, in _step
    loss = self.loss(y_hat, self._cast_type_to_loss(y))  # Shape mismatch for binary: need to 'y = y.unsqueeze(1)' (or use .reshape(2)) to cast from [2] to [2,1] and cast y to float with .float()
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 734, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "/home/geonatureadmin/malpolon/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 3242, in binary_cross_entropy_with_logits
    raise ValueError(f"Target size ({target.size()}) must be the same as input size ({input.size()})")
ValueError: Target size (torch.Size([2, 1])) must be the same as input size (torch.Size([2, 5]))

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

I don't know what is the problem and I arrive at the limit of what my current knowledge permit me to do.
Do you think you can give me help ?

Thank you in advance,

**Comment by PNPyrenees** [comment]
Sorry, I got it !

I was needed to change the data.num_classes parameter like this :

`num_classes: &num_classes 1`

because I work on one only one species.

It's running hope everything gonna be alright

**Comment by herve-goeau** [comment]
Thank you very much for your contribution. Please do not hesitate to contact the team if you need more information on this subject.
